sudo: false
language: python
cache: pip
python:
- '2.7'
- '3.5'
addons:
  apt:
    packages:
    - protobuf-compiler
    - protobuf-c-compiler
    - python-protobuf
install:
- pip install -r requirements.txt
- pip install pylint
script:
- pylint -j 2 pokecli.py pokemongo_bot
- python pokecli.py --auth-service=google --username=$POGO_GOOGLE_USERNAME --password=$POGO_GOOGLE_PASSWORD --location=40.782613,-73.9752687 --mode=all --walk=4 & PID=$!
- sleep 300
- kill -HUP $PID
notifications:
  slack:
    secure: OVA5zqmalbyJb0H5+zeLJpcxf6Vx7lDunn/PcZHRKnSACFgygSgY4Hq0Nc97E4noIj2COQFEMO8qmpIQ5U2vxZ1hovguM/xZ5q0fdPdRM47ID3q3GIyuPxy+7rAEES5vrID9fswfKV2N60BRy98PeTzexNST6wMTDIJdTRapmnFKqt9ketE3n4bbjGvUm6NZiQ06V6SPuA0BWzabmCuAwfh655ve37SclFABagjZ0oWqUsYtwElcrXM2fnyz/u3pkLKzMUQ5RRheXUpdZOxMvJ8nQnckh4hyDPEbPEt1VFblERUJPBd2WSNhmmvMLgbbCvDHIBaGW0Dqf0c7/DopWFReIxYMOCau8jycbMN5Xx4xZ6DA8KSXOOi9kNIPTtn5AbOOE6t3wugTcCKI7kX/O1FMUHxvhXNxI+fGBQSwIw5csu/SL8ZlHv1EFIVhVI1eFpuCAudQYGEuPv6jvBLBtRb+5zu2VTJ8qADqPGAp6VqXoZ9XHOWBwrhAR/F14Jk6cDCHAoHC/sUbns9AmUnQOz19ugtoEq7NQkB53fENbC+DN+IO9YyCwnCV9rqQLlxt4qN9cQ985yzh7O4T5csd3Utc0wqtvn7100SY3sbhu2I842aYp8qqYF4UrTl6oCL3Z14aIfKLeI/MTknbdqF8uZGwBsHpjZtAzgO3EsCNDbU=
env:
  global:
  - secure: qpkylrQNjxolrQMFkEOsbMNjwZRd81VMGQTXYKR6pj3M+kHHmWPkDQzENcD/WOEdTOwvTjlAJYDnA3XPc5W9U2HzNszZWPbKpkSA98Ly31DJ+fLqXYYz0p+gn5LIQDsY2BOlIpCPeIETGhZ1yTewiW6G7dWmRNwz1O6ogjFfUPUy0mmivTP3vt+5JRlD+nymb7BWprX5dPLbKnqc/usW8Gv1wwWRGfRqslqVOz43naWsH4zJxXH2xE9hCXBOzBNg/rveZMv+pfbZOm07iZdIoXu7nBCjXUorq0WlXUaUAJS+e6HwFJYh8WPNS4vpLpIg/IIm3uQiFsDCZZx92BnzSjtf4dLXPSFQ98adL9AhzdSmi4g0w0AaoNcjDrIopCVlbDqqSnGvZK8fnShnDgse3XB8amlBiueDF2Gq/3c9a1m/NCRCY22ReuILUX2D8yNpjl2qX9pkAiUwPBiX5e+2ZRoKf6TzG1aidA4mvWw2bIxG8uVlbZc3s/A86FGeLhimBo0IY7tjNf8vuuBT73d4piqFxZ604ApSbroxAbFwa6E29UsQ27OSt+yoN3qa6kRUxwMPWYmCK14nkMbH5Op+J8QkJQAs8DKSuB3jnroKUpRogf1P4IuH7A6L1Lj5aaE5izp40ivkfLkFbfOAjkGSpxoX7IUsQZlKOKgac6NugdE=
  - secure: Fffo04ox20ojX9KRxmoJCAyJ5ktwZUvftZiIap6pQtUC5nd5W4+n0ZEMGPyfsBUNVxibaQmCllSpwY7quXseGX53Y3jI5jHORsKflnHxabhlLnm0bogUu/KhfAEMWGy/S4KbC503KAITmF6av/b1qur1HYxKGWomXpf2JdRKOJeqBz9CnqbqR40/nCvaKa7RxSXZJBhbr8ujKgtrgX9ZhxBH+umpmLamFKe9LCaPlkIxt4W9V40Q+fw4Gu/ztk1jeM7JLm2idPtwKLvf5bmIi9LzdhnWalySmb8DeW1KG0W8yzatJRw5BWVK98snyJ1LR9UBfXTIjDaE3prQmIywVhylaLibrfL/QrbrYr6eQtU4DfA3kTpF9pQ2Ur+JusEsTQrmBtdyg5lovKWVu+t8QVFXM3Hz6mQ3b4qjyzyu+5NGwD8uqLAHZSKc66SdgHv4yy8AU6sswXqCvaiAfdtWrVGfXTDbVK91nBTzfWJqrJYm8Tr7tlRCteQVDAUn9ZKf36TbCqGi4ZigdDw2SiAd2P8s/zTrfryFJGVfHvWez46Iouz0vCPexz6N/4R7HuDZ1TaqxURcKqmwIi1AwxeK/vJ7YF1D9fEv3ZsUcMDGiBneh5qaYqC1g4KxrtEYSAJUgkIYSgvpoZSB6igMc4XPy1/+Fdly/Dbm5MGQ0bFB42w=
